version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html/

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
